"""add page sections

Revision ID: 7fcec3e238c9
Revises: ef0497006576
Create Date: 2026-05-31 17:47:35.526831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcec3e238c9'
down_revision = 'ef0497006576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('sections')

    # ### end Alembic commands ###
